### ISSUE TITLE
CLI Logging Levels

### ISSUE THREAD

**Issue by dOrgJelli** [polywrap/toolchain#99]
Enable different logging levels within the CLI, such as `--verbose` and `--quiet`. This is dependent on: https://github.com/Web3-API/monorepo/issues/187 & https://github.com/Web3-API/monorepo/issues/185

**Comment by fetsorn** [comment]
While working on workflow tests I noticed that `polywrap run` needs at least two logging levels.
 - Warning: show only failed jobs and validations
 - Info: show all jobs and validations
Picking this one up.
